version: '3.8'

services:
  # Global PocketBase instance
  pb_global:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: fathom_pb_global
    restart: unless-stopped
    ports:
      - "${PB_GLOBAL_PORT:-8090}:8090"
    volumes:
      - global_pb_data:/pb_data
      - ./pb_migrations:/pb_migrations
    environment:
      - PB_ENCRYPTION_KEY=${PB_ENCRYPTION_KEY}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fathom_network

  # Backend service (Rust binary)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: runtime
    container_name: fathom_backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - DATABASE_URL=http://pb_global:8090
      - AES_MASTER_KEY=${AES_MASTER_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:8080}
      - USER_DB_BASE_PATH=${USER_DB_BASE_PATH:-/app/user_dbs}
      - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL}
      - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD}
      - PB_ENCRYPTION_KEY=${PB_ENCRYPTION_KEY}
    volumes:
      - user_db_data:/app/user_dbs
      - ./logs:/app/logs
      # Optional: bind mount for development hot reload
      # - ./backend/src:/app/backend/src:ro
    depends_on:
      pb_global:
        condition: service_healthy
    networks:
      - fathom_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Worker service (same image as backend but runs fathom_to_loom_worker)
  worker:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: runtime
    container_name: fathom_worker
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - DATABASE_URL=http://pb_global:8090
      - AES_MASTER_KEY=${AES_MASTER_KEY}
      - WORKER_CONCURRENCY=${WORKER_CONCURRENCY:-1}
      - QUEUE_POLL_INTERVAL=${QUEUE_POLL_INTERVAL:-5}
      - USER_DB_BASE_PATH=${USER_DB_BASE_PATH:-/app/user_dbs}
      - PB_ENCRYPTION_KEY=${PB_ENCRYPTION_KEY}
    volumes:
      - user_db_data:/app/user_dbs
      - ./logs:/app/logs
    command: ["/app/fathom_to_loom_worker"]
    depends_on:
      pb_global:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - fathom_network

  # Frontend service (Nginx serving dist/ from Dioxus build)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: runtime
    container_name: fathom_frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    env_file:
      - .env
    environment:
      - API_BASE_URL=${API_BASE_URL:-http://backend:3000}
    depends_on:
      - backend
    networks:
      - fathom_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Development frontend service with hot reload (alternative to production frontend)
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: dev
    container_name: fathom_frontend_dev
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-8080}:8080"
    env_file:
      - .env
    environment:
      - API_BASE_URL=${API_BASE_URL:-http://backend:3000}
    volumes:
      # Bind mount for hot reload in development
      - ./frontend/src:/app/frontend/src
      - ./frontend/assets:/app/frontend/assets
      - ./frontend/Dioxus.toml:/app/frontend/Dioxus.toml
    depends_on:
      - backend
    networks:
      - fathom_network
    profiles:
      - dev

  # Nginx reverse proxy (production)
  nginx:
    image: nginx:alpine
    container_name: fathom_nginx
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
      # Optional: serve static files directly from nginx
      - frontend_dist:/var/www/html:ro
    depends_on:
      - backend
      - frontend
      - pb_global
    networks:
      - fathom_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - production

  # Optional: Process supervisor for per-user PBs (watch script alternative)
  pb-supervisor:
    build:
      context: .
      dockerfile: Dockerfile.supervisor
    container_name: fathom_pb_supervisor
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - DATABASE_URL=http://pb_global:8090
      - AES_MASTER_KEY=${AES_MASTER_KEY}
      - USER_DB_BASE_PATH=${USER_DB_BASE_PATH:-/app/user_dbs}
      - PB_ENCRYPTION_KEY=${PB_ENCRYPTION_KEY}
    volumes:
      - user_db_data:/app/user_dbs
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock  # For spawning per-user PB containers
    depends_on:
      pb_global:
        condition: service_healthy
    networks:
      - fathom_network
    profiles:
      - supervisor

volumes:
  global_pb_data:
    driver: local
  user_db_data:
    driver: local
  frontend_dist:
    driver: local

networks:
  fathom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
